---
driver:
  name: vagrant
#  network:
#    - - forwarded_port
#      - guest: 5555
#        host: 5454
#        auto_correct: true
#    - - forwarded_port
#      - guest: 443
#        host: 4443
#        auto_correct: true
#    - - forwarded_port
#      - guest: 8880
#        host: 80
#        auto_correct: true

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
    driver:
      #box: bento/ubuntu-14.04
      box: bento/ubuntu-14.04-i386
  - name: centos-6.7
    driver:
      #box: bento/centos-6.7
      box: bento/centos-6.7-i386

suites:
  - name: flower
    run_list:
      - recipe[flower-test::default]
    attributes:
