---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    driver_config:
      network:
      - ["forwarded_port", {"guest": 5555, "host": 5454}]
      - ["forwarded_port", {"guest": 443, "host": 3443}]
      - ["forwarded_port", {"guest": 80, "host": 3980}]
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  - name: centos-6.5
    driver_config:
      network:
      - ["forwarded_port", {"guest": 5555, "host": 5353}]
      - ["forwarded_port", {"guest": 443, "host": 4443}]
      - ["forwarded_port", {"guest": 80, "host": 4080}]
    box: opscode-centos-6.5
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box

suites:
  - name: flower
    run_list:
      - recipe[flower-test::default]
    attributes:
